//! Wire types for the x402 protocol.
//!
//! Two structures cross the HTTP boundary:
//!
//! - [`PaymentChallenge`] — server → client in the `402` body.
//!   Tells the client what to sign.
//! - [`PaymentPayload`] — client → server in the `X-PAYMENT` header
//!   (base64-encoded bytes per EIP-3009). Contains the signed
//!   authorization.
//!
//! Plus one server-internal marker:
//!
//! - [`X402Paid`] — attached to the request extensions after successful
//!   settlement so downstream handlers know who paid what.

use ethereum_types::{H160, H256, U256};
use serde::{Deserialize, Serialize};

/// The `402` challenge body the server returns when a request arrives
/// without a valid payment header. Serialized as JSON under a top-level
/// `"x402"` key, with an optional `"reason"` sibling for rejected
/// retries.
///
/// See `x402_payment.feature` scenario #1 for the canonical field list.
/// Protocol version field (`version`) is `1` for this implementation;
/// future transport changes bump this.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentChallenge {
    /// Protocol version. Always `1` in this release.
    pub version: u8,
    /// Address of `X402Facilitator` on the target chain.
    pub facilitator: String,
    /// Address of `WrappedSALT` (the ERC-20 the client signs against).
    pub token: String,
    /// Numeric chain ID — `40204` for Citrate testnet.
    pub chain_id: u64,
    /// Amount in wei (decimal string — JSON number would lose precision
    /// for amounts > 2^53).
    pub amount: String,
    /// Server-generated nonce (32-byte hex, `0x`-prefixed).
    pub nonce: String,
    /// Unix timestamp before which the signed authorization is invalid.
    pub valid_after: u64,
    /// Unix timestamp after which the signed authorization is invalid.
    /// Server sets this to `valid_after + 300s` by default.
    pub valid_before: u64,
    /// Treasury / recipient address (where net value lands after the
    /// facilitator's fee cut).
    pub recipient: String,
    /// Pre-computed EIP-712 digest the client must sign. Hex-encoded
    /// 32 bytes, `0x`-prefixed. Equal to
    /// `keccak256("\x19\x01" || DOMAIN_SEPARATOR || STRUCT_HASH)`.
    pub digest: String,
}

/// Parsed contents of an `X-PAYMENT` header. The header carries 265
/// bytes (base64-encoded) in the layout precompile `0x0201`
/// (`TransferAuthVerify`) expects:
///
/// `from(20) | to(20) | value(32) | validAfter(32) | validBefore(32) | nonce(32) | v(1) | r(32) | s(32) = 265 bytes`
///
/// We preserve the same byte layout so `verify_offline()` can forward
/// the bytes directly to the precompile without re-serialization.
#[derive(Debug, Clone)]
pub struct PaymentPayload {
    /// Payer — the `from` field of the EIP-3009 authorization.
    pub from: H160,
    /// Recipient — usually the facilitator or a designated treasury.
    pub to: H160,
    /// Amount in wei.
    pub value: U256,
    /// Unix timestamp before which the authorization is invalid.
    pub valid_after: U256,
    /// Unix timestamp after which the authorization is invalid.
    pub valid_before: U256,
    /// 32-byte nonce generated by the server's prior challenge.
    pub nonce: H256,
    /// ECDSA signature component `v`.
    pub v: u8,
    /// ECDSA signature component `r`.
    pub r: H256,
    /// ECDSA signature component `s`.
    pub s: H256,
}

impl PaymentPayload {
    /// Serialize to the 265-byte wire format the precompile expects.
    /// This is the inverse of [`Self::parse`].
    pub fn to_bytes(&self) -> Vec<u8> {
        let _ = self;
        todo!("WP-02.3: emit the 265-byte layout described in module docs")
    }

    /// Parse from the 265-byte wire format. Returns `Err` on length
    /// mismatch; higher layers decode from base64 first.
    pub fn parse(_bytes: &[u8]) -> Result<Self, crate::X402Error> {
        todo!("WP-02.3: parse the 265-byte layout described in module docs")
    }
}

/// Attached to the request's extensions after `X402Layer` settles a
/// payment. Wrapped handlers can read it via
/// `req.extensions().get::<X402Paid>()` to learn the payer and amount.
#[derive(Debug, Clone)]
pub struct X402Paid {
    /// Who paid.
    pub payer: H160,
    /// How much, in wei (grains). Display layers convert via
    /// `citrate_wallet_core::format::grains_to_salt` before showing.
    pub amount_wei: U256,
    /// The nonce that was settled. Useful for trail logs and dispute
    /// correlation.
    pub nonce: H256,
    /// The on-chain transaction hash of the `settlePayment` call.
    pub settle_tx_hash: H256,
}
