//! Wire types for the x402 protocol.
//!
//! Two structures cross the HTTP boundary:
//!
//! - [`PaymentChallenge`] — server → client in the `402` body.
//!   Tells the client what to sign.
//! - [`PaymentPayload`] — client → server in the `X-PAYMENT` header
//!   (base64-encoded bytes per EIP-3009). Contains the signed
//!   authorization.
//!
//! Plus one server-internal marker:
//!
//! - [`X402Paid`] — attached to the request extensions after successful
//!   settlement so downstream handlers know who paid what.

use ethereum_types::{H160, H256, U256};
use serde::{Deserialize, Serialize};

/// The `402` challenge body the server returns when a request arrives
/// without a valid payment header. Serialized as JSON under a top-level
/// `"x402"` key, with an optional `"reason"` sibling for rejected
/// retries.
///
/// See `x402_payment.feature` scenario #1 for the canonical field list.
/// Protocol version field (`version`) is `1` for this implementation;
/// future transport changes bump this.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentChallenge {
    /// Protocol version. Always `1` in this release.
    pub version: u8,
    /// Address of `X402Facilitator` on the target chain.
    pub facilitator: String,
    /// Address of `WrappedSALT` (the ERC-20 the client signs against).
    pub token: String,
    /// Numeric chain ID — `40204` for Citrate testnet.
    pub chain_id: u64,
    /// Amount in wei (decimal string — JSON number would lose precision
    /// for amounts > 2^53).
    pub amount: String,
    /// Server-generated nonce (32-byte hex, `0x`-prefixed).
    pub nonce: String,
    /// Unix timestamp before which the signed authorization is invalid.
    pub valid_after: u64,
    /// Unix timestamp after which the signed authorization is invalid.
    /// Server sets this to `valid_after + 300s` by default.
    pub valid_before: u64,
    /// Treasury / recipient address (where net value lands after the
    /// facilitator's fee cut).
    pub recipient: String,
    /// Pre-computed EIP-712 digest the client must sign. Hex-encoded
    /// 32 bytes, `0x`-prefixed. Equal to
    /// `keccak256("\x19\x01" || DOMAIN_SEPARATOR || STRUCT_HASH)`.
    pub digest: String,
    /// Keccak commitment to the exact method, path/query, and body this
    /// challenge authorizes. The gateway checks it again on the paid retry.
    #[serde(default)]
    pub request_hash: String,
}

/// Parsed contents of an `X-PAYMENT` header. The header carries 265
/// bytes (base64-encoded) in the layout precompile `0x0201`
/// (`TransferAuthVerify`) expects:
///
/// `from(20) | to(20) | value(32) | validAfter(32) | validBefore(32) | nonce(32) | v(1) | r(32) | s(32) = 265 bytes`
///
/// We preserve the same byte layout so `verify_offline()` can forward
/// the bytes directly to the precompile without re-serialization.
#[derive(Debug, Clone)]
pub struct PaymentPayload {
    /// Payer — the `from` field of the EIP-3009 authorization.
    pub from: H160,
    /// Recipient — usually the facilitator or a designated treasury.
    pub to: H160,
    /// Amount in wei.
    pub value: U256,
    /// Unix timestamp before which the authorization is invalid.
    pub valid_after: U256,
    /// Unix timestamp after which the authorization is invalid.
    pub valid_before: U256,
    /// 32-byte nonce generated by the server's prior challenge.
    pub nonce: H256,
    /// ECDSA signature component `v`.
    pub v: u8,
    /// ECDSA signature component `r`.
    pub r: H256,
    /// ECDSA signature component `s`.
    pub s: H256,
}

/// Wire size of a [`PaymentPayload`] in bytes:
/// `from(20) + to(20) + value(32) + validAfter(32) + validBefore(32) + nonce(32) + v(1) + r(32) + s(32)`
pub const PAYLOAD_BYTES: usize = 20 + 20 + 32 + 32 + 32 + 32 + 1 + 32 + 32;

impl PaymentPayload {
    /// Serialize to the 233-byte wire format. This is what goes into
    /// the `X-PAYMENT` header (after base64 encoding).
    ///
    /// The precompile `0x0201` expects a 265-byte input: this payload
    /// PREFIXED with the 32-byte EIP-712 domain separator. The server
    /// supplies the domain separator from its own config — the client
    /// never has to know about it.
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(PAYLOAD_BYTES);
        out.extend_from_slice(self.from.as_bytes());
        out.extend_from_slice(self.to.as_bytes());
        let mut buf32 = [0u8; 32];
        self.value.to_big_endian(&mut buf32);
        out.extend_from_slice(&buf32);
        self.valid_after.to_big_endian(&mut buf32);
        out.extend_from_slice(&buf32);
        self.valid_before.to_big_endian(&mut buf32);
        out.extend_from_slice(&buf32);
        out.extend_from_slice(self.nonce.as_bytes());
        out.push(self.v);
        out.extend_from_slice(self.r.as_bytes());
        out.extend_from_slice(self.s.as_bytes());
        debug_assert_eq!(out.len(), PAYLOAD_BYTES);
        out
    }

    /// Parse from the 233-byte wire format.
    ///
    /// Returns [`crate::X402Error::MalformedPaymentHeader`] on length
    /// mismatch. Higher layers decode from base64 first.
    pub fn parse(bytes: &[u8]) -> Result<Self, crate::X402Error> {
        if bytes.len() != PAYLOAD_BYTES {
            return Err(crate::X402Error::MalformedPaymentHeader(format!(
                "expected {} bytes, got {}",
                PAYLOAD_BYTES,
                bytes.len()
            )));
        }
        let mut cursor = 0;
        let mut take = |n: usize| {
            let slice = &bytes[cursor..cursor + n];
            cursor += n;
            slice
        };
        let from = H160::from_slice(take(20));
        let to = H160::from_slice(take(20));
        let value = U256::from_big_endian(take(32));
        let valid_after = U256::from_big_endian(take(32));
        let valid_before = U256::from_big_endian(take(32));
        let nonce = H256::from_slice(take(32));
        let v = take(1)[0];
        let r = H256::from_slice(take(32));
        let s = H256::from_slice(take(32));
        Ok(PaymentPayload {
            from,
            to,
            value,
            valid_after,
            valid_before,
            nonce,
            v,
            r,
            s,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> PaymentPayload {
        PaymentPayload {
            from: H160::from([0xa1; 20]),
            to: H160::from([0xa2; 20]),
            value: U256::from(1_000_000_000_000_000_000u128),
            valid_after: U256::from(1_714_000_000u64),
            valid_before: U256::from(1_714_000_300u64),
            nonce: H256::from([0xde; 32]),
            v: 27,
            r: H256::from([0xab; 32]),
            s: H256::from([0xcd; 32]),
        }
    }

    #[test]
    fn payload_round_trip() {
        let p = sample();
        let bytes = p.to_bytes();
        assert_eq!(bytes.len(), PAYLOAD_BYTES);
        let parsed = PaymentPayload::parse(&bytes).expect("parse");
        assert_eq!(parsed.from, p.from);
        assert_eq!(parsed.to, p.to);
        assert_eq!(parsed.value, p.value);
        assert_eq!(parsed.valid_after, p.valid_after);
        assert_eq!(parsed.valid_before, p.valid_before);
        assert_eq!(parsed.nonce, p.nonce);
        assert_eq!(parsed.v, p.v);
        assert_eq!(parsed.r, p.r);
        assert_eq!(parsed.s, p.s);
    }

    #[test]
    fn parse_rejects_wrong_length() {
        let err = PaymentPayload::parse(&[0u8; 100]).expect_err("should fail");
        assert!(matches!(err, crate::X402Error::MalformedPaymentHeader(_)));
    }

    #[test]
    fn parse_rejects_empty() {
        let err = PaymentPayload::parse(&[]).expect_err("should fail");
        assert!(matches!(err, crate::X402Error::MalformedPaymentHeader(_)));
    }

    #[test]
    fn payload_size_matches_precompile_minus_domain() {
        // Precompile 0x0201 (TransferAuthVerify) expects 265 bytes
        // = 32 (domain separator) + 233 (this payload). Locked here
        // so any drift in either side surfaces immediately.
        assert_eq!(PAYLOAD_BYTES, 265 - 32);
    }
}

/// Attached to the request's extensions after `X402Layer` settles a
/// payment. Wrapped handlers can read it via
/// `req.extensions().get::<X402Paid>()` to learn the payer and amount.
#[derive(Debug, Clone)]
pub struct X402Paid {
    /// Who paid.
    pub payer: H160,
    /// How much, in wei (grains). Display layers convert via
    /// `citrate_wallet_core::format::grains_to_salt` before showing.
    pub amount_wei: U256,
    /// The nonce that was settled. Useful for trail logs and dispute
    /// correlation.
    pub nonce: H256,
    /// The on-chain transaction hash of the `settlePayment` call.
    pub settle_tx_hash: H256,
}
